baseurl: "/"
title: "Rae Gaines"
init_js: "js/init.js"
page_load_js: "js/page-load.js"
page_unload_js: "js/page-unload.js"
params:
  color_scheme: light
  accent_color: pink
  header:
    title: Rae Gaines
    has_nav: true
    nav_links:
      - label: Home
        url: /
        style: link
      - label: Portfolio
        url: /portfolio/
        style: link
      # - label: Blog
      #   url: /blog/
        # style: link
      # - label: Style Guide
      #   url: /style-guide/
      #   style: link
      - label: About
        url: /about/
        style: link
      - label: Contact
        url: /contact/
        style: link
  footer:
    content: >-
      &copy; Rae Gaines with a GNU General Public License. This Jamstack site was created with <a href="https://www.stackbit.com/?utm_source=deployed-footer">Stackbit</a>.
    has_social: true
    social_links:
      - label: Twitter
        url: https://twitter.com/rudietoos
        style: icon
        icon: twitter
        new_window: true
      - label: Instagram
        url: https://www.instagram.com/rudietuesdays
        style: icon
        icon: instagram
        new_window: true
      - label: LinkedIn
        url: https://www.linkedin.com/in/againes
        style: icon
        icon: linkedin
        new_window: true
sass:
  input_file: sass/main.scss
  output_file: css/main.css
  indentWidth: 4
  outputStyle: nested
  precision: 10
templates:
  body_class: "palette-{{ site.params.color_scheme }} accent-{{ site.params.accent_color }}"
